// <auto-generated />
namespace ChildCentre.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_local_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_local_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201404091544464_update_local_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
